Migrate workflow engine to Flowable (#85).
WrenSecurity/wrenidm pull request #172
Opened 2024-02-19 11:16 UTC by karelmaxa

This PR introduces the migration from the Activiti workflow engine to the Flowable engine. The migration is to version 6.7 because version 6.8 requires a newer OSGi specification and the new major version (7) is Java 17+ only. I expect the migration to the latest Flowable release to take place shortly after this PR.

One of the benefits of this change is that it allows us to upgrade other dependencies such as Groovy or Apache Felix.

The new version has been fully tested with the integration tests defined in the [wrenidm-test](https://github.com/orchitech/wrenidm-test) project.

**Breaking changes**

All process definitions must be migrated to use Flowable annotations. Migration instructions will be available later in the Wren:IDM Migration Guide.

2024-02-19 13:40 UTC, pavelhoral commented
Please check if and how this should be covered by the semi-automated upgrade process (openidm-maintenance).

2024-02-19 14:05 UTC, pavelhoral requested changes

2024-02-21 07:24 UTC, karelmaxa commented on wrenidm-workflow-flowable/src/main/java/org/wrensecurity/wrenidm/workflow/flowable/WorkflowServiceImpl.java
> +package org.wrensecurity.wrenidm.workflow.flowable;
Yes, I agree. The package `impl` has been taken back.

2024-02-21 07:26 UTC, karelmaxa commented on wrenidm-workflow-flowable/src/main/java/org/wrensecurity/wrenidm/workflow/flowable/WorkflowResource.java
> +public class WorkflowResource implements RequestHandler {
OK, the class prefix has been changed to Flowable.

2024-02-21 12:15 UTC, karelmaxa commented on wrenidm-workflow-flowable/src/main/java/org/wrensecurity/wrenidm/workflow/flowable/WorkflowServiceImpl.java
> +                    engineProperties.put("wrenidm.flowable.engine", "true");
This is only used in this place, so in my opinion the constant is not necessary.

2024-02-21 12:16 UTC, karelmaxa commented
As I wrote above, I will try to prepare migration notes including necessary changes in the IdM configuration and migration of the BPMN process definitions.

2024-02-21 16:02 UTC, pavelhoral approved these changes
LGTM

2024-02-21 16:02 UTC, merged